### ISSUE TITLE
[Bug] 删除文件逻辑不立刻执行

### ISSUE THREAD

**Issue by c0ldheart** [LinLin00000000/Pake#2]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

-

### System version

-

### Node.js version

-

### Minimal reproduce step

1. 在截图文件夹增加新文件后，该文件不被删除
2. 再次添加新文件后，步骤1中新增的文件3秒后被删除

### What did you expect to see?

在截图文件夹增加新文件后，一段时间内自动删除

### What did you see instead?

见reproduce step

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by LinLin00000000** [comment]
This is indeed a good issue.
The original intent of the code was to automatically delete the file after 3 seconds of a successful screenshot, but as you said it is somewhat problematic.
You are more than welcome to submit a pr, it would be a good idea to build it locally first and test if your changes solve the problem : )

**Comment by LinLin00000000** [comment]
Well done!
